
use wbdaten;

INSERT IGNORE INTO His_RezeptSchritte (H_RS_RZ_Nr,H_RS_RZ_Variante_Nr,H_RS_Index,H_RS_Aenderung_Nr,H_RS_Schritt_Nr,H_RS_Ko_Nr,H_RS_ParamNr,H_RS_Wert,H_RS_Wert_Prod,H_RS_Par1,H_RS_Par2,H_RS_Par3,H_RS_Preis,H_RS_PreisEinheit) VALUES (-98,1,1,0,1,1021,1,'Kocher Schritt 1',NULL,NULL,NULL,NULL,NULL,0);
INSERT IGNORE INTO His_RezeptSchritte (H_RS_RZ_Nr,H_RS_RZ_Variante_Nr,H_RS_Index,H_RS_Aenderung_Nr,H_RS_Schritt_Nr,H_RS_Ko_Nr,H_RS_ParamNr,H_RS_Wert,H_RS_Wert_Prod,H_RS_Par1,H_RS_Par2,H_RS_Par3,H_RS_Preis,H_RS_PreisEinheit) VALUES (-98,1,2,0,2,1006,1,'00:00:00',NULL,NULL,NULL,NULL,NULL,0);
INSERT IGNORE INTO His_RezeptSchritte (H_RS_RZ_Nr,H_RS_RZ_Variante_Nr,H_RS_Index,H_RS_Aenderung_Nr,H_RS_Schritt_Nr,H_RS_Ko_Nr,H_RS_ParamNr,H_RS_Wert,H_RS_Wert_Prod,H_RS_Par1,H_RS_Par2,H_RS_Par3,H_RS_Preis,H_RS_PreisEinheit) VALUES (-98,1,3,0,3,1001,1,'00:00:00',NULL,NULL,NULL,NULL,NULL,0);
INSERT IGNORE INTO His_RezeptSchritte (H_RS_RZ_Nr,H_RS_RZ_Variante_Nr,H_RS_Index,H_RS_Aenderung_Nr,H_RS_Schritt_Nr,H_RS_Ko_Nr,H_RS_ParamNr,H_RS_Wert,H_RS_Wert_Prod,H_RS_Par1,H_RS_Par2,H_RS_Par3,H_RS_Preis,H_RS_PreisEinheit) VALUES (-98,1,4,0,4,1002,1,'00:00:00',NULL,NULL,NULL,NULL,NULL,0);
INSERT IGNORE INTO His_RezeptSchritte (H_RS_RZ_Nr,H_RS_RZ_Variante_Nr,H_RS_Index,H_RS_Aenderung_Nr,H_RS_Schritt_Nr,H_RS_Ko_Nr,H_RS_ParamNr,H_RS_Wert,H_RS_Wert_Prod,H_RS_Par1,H_RS_Par2,H_RS_Par3,H_RS_Preis,H_RS_PreisEinheit) VALUES (-98,1,5,0,5,1011,1,'50',NULL,NULL,NULL,NULL,NULL,0);
INSERT IGNORE INTO His_RezeptSchritte (H_RS_RZ_Nr,H_RS_RZ_Variante_Nr,H_RS_Index,H_RS_Aenderung_Nr,H_RS_Schritt_Nr,H_RS_Ko_Nr,H_RS_ParamNr,H_RS_Wert,H_RS_Wert_Prod,H_RS_Par1,H_RS_Par2,H_RS_Par3,H_RS_Preis,H_RS_PreisEinheit) VALUES (-98,1,6,0,6,1008,1,'0',NULL,NULL,NULL,NULL,NULL,0);
INSERT IGNORE INTO His_RezeptSchritte (H_RS_RZ_Nr,H_RS_RZ_Variante_Nr,H_RS_Index,H_RS_Aenderung_Nr,H_RS_Schritt_Nr,H_RS_Ko_Nr,H_RS_ParamNr,H_RS_Wert,H_RS_Wert_Prod,H_RS_Par1,H_RS_Par2,H_RS_Par3,H_RS_Preis,H_RS_PreisEinheit) VALUES (-98,1,7,0,7,1005,1,'0,0',NULL,NULL,NULL,NULL,NULL,0);
INSERT IGNORE INTO His_RezeptSchritte (H_RS_RZ_Nr,H_RS_RZ_Variante_Nr,H_RS_Index,H_RS_Aenderung_Nr,H_RS_Schritt_Nr,H_RS_Ko_Nr,H_RS_ParamNr,H_RS_Wert,H_RS_Wert_Prod,H_RS_Par1,H_RS_Par2,H_RS_Par3,H_RS_Preis,H_RS_PreisEinheit) VALUES (-98,1,8,0,8,1004,1,'0,0',NULL,NULL,NULL,NULL,NULL,0);
INSERT IGNORE INTO His_RezeptSchritte (H_RS_RZ_Nr,H_RS_RZ_Variante_Nr,H_RS_Index,H_RS_Aenderung_Nr,H_RS_Schritt_Nr,H_RS_Ko_Nr,H_RS_ParamNr,H_RS_Wert,H_RS_Wert_Prod,H_RS_Par1,H_RS_Par2,H_RS_Par3,H_RS_Preis,H_RS_PreisEinheit) VALUES (-98,1,9,0,9,1003,1,'0,0',NULL,NULL,NULL,NULL,NULL,0);

INSERT IGNORE INTO His_RezeptSchritte (H_RS_RZ_Nr,H_RS_RZ_Variante_Nr,H_RS_Index,H_RS_Aenderung_Nr,H_RS_Schritt_Nr,H_RS_Ko_Nr,H_RS_ParamNr,H_RS_Wert,H_RS_Wert_Prod,H_RS_Par1,H_RS_Par2,H_RS_Par3,H_RS_Preis,H_RS_PreisEinheit) VALUES (-98,1,10,0,10,1022,1,'Kocher Schritt 2',NULL,NULL,NULL,NULL,NULL,0);
INSERT IGNORE INTO His_RezeptSchritte (H_RS_RZ_Nr,H_RS_RZ_Variante_Nr,H_RS_Index,H_RS_Aenderung_Nr,H_RS_Schritt_Nr,H_RS_Ko_Nr,H_RS_ParamNr,H_RS_Wert,H_RS_Wert_Prod,H_RS_Par1,H_RS_Par2,H_RS_Par3,H_RS_Preis,H_RS_PreisEinheit) VALUES (-98,1,11,0,11,1006,1,'00:00:00',NULL,NULL,NULL,NULL,NULL,0);
INSERT IGNORE INTO His_RezeptSchritte (H_RS_RZ_Nr,H_RS_RZ_Variante_Nr,H_RS_Index,H_RS_Aenderung_Nr,H_RS_Schritt_Nr,H_RS_Ko_Nr,H_RS_ParamNr,H_RS_Wert,H_RS_Wert_Prod,H_RS_Par1,H_RS_Par2,H_RS_Par3,H_RS_Preis,H_RS_PreisEinheit) VALUES (-98,1,12,0,12,1001,1,'00:00:00',NULL,NULL,NULL,NULL,NULL,0);
INSERT IGNORE INTO His_RezeptSchritte (H_RS_RZ_Nr,H_RS_RZ_Variante_Nr,H_RS_Index,H_RS_Aenderung_Nr,H_RS_Schritt_Nr,H_RS_Ko_Nr,H_RS_ParamNr,H_RS_Wert,H_RS_Wert_Prod,H_RS_Par1,H_RS_Par2,H_RS_Par3,H_RS_Preis,H_RS_PreisEinheit) VALUES (-98,1,13,0,13,1002,1,'00:00:00',NULL,NULL,NULL,NULL,NULL,0);
INSERT IGNORE INTO His_RezeptSchritte (H_RS_RZ_Nr,H_RS_RZ_Variante_Nr,H_RS_Index,H_RS_Aenderung_Nr,H_RS_Schritt_Nr,H_RS_Ko_Nr,H_RS_ParamNr,H_RS_Wert,H_RS_Wert_Prod,H_RS_Par1,H_RS_Par2,H_RS_Par3,H_RS_Preis,H_RS_PreisEinheit) VALUES (-98,1,14,0,14,1011,1,'50',NULL,NULL,NULL,NULL,NULL,0);
INSERT IGNORE INTO His_RezeptSchritte (H_RS_RZ_Nr,H_RS_RZ_Variante_Nr,H_RS_Index,H_RS_Aenderung_Nr,H_RS_Schritt_Nr,H_RS_Ko_Nr,H_RS_ParamNr,H_RS_Wert,H_RS_Wert_Prod,H_RS_Par1,H_RS_Par2,H_RS_Par3,H_RS_Preis,H_RS_PreisEinheit) VALUES (-98,1,15,0,15,1008,1,'0',NULL,NULL,NULL,NULL,NULL,0);
INSERT IGNORE INTO His_RezeptSchritte (H_RS_RZ_Nr,H_RS_RZ_Variante_Nr,H_RS_Index,H_RS_Aenderung_Nr,H_RS_Schritt_Nr,H_RS_Ko_Nr,H_RS_ParamNr,H_RS_Wert,H_RS_Wert_Prod,H_RS_Par1,H_RS_Par2,H_RS_Par3,H_RS_Preis,H_RS_PreisEinheit) VALUES (-98,1,16,0,16,1005,1,'0,0',NULL,NULL,NULL,NULL,NULL,0);
INSERT IGNORE INTO His_RezeptSchritte (H_RS_RZ_Nr,H_RS_RZ_Variante_Nr,H_RS_Index,H_RS_Aenderung_Nr,H_RS_Schritt_Nr,H_RS_Ko_Nr,H_RS_ParamNr,H_RS_Wert,H_RS_Wert_Prod,H_RS_Par1,H_RS_Par2,H_RS_Par3,H_RS_Preis,H_RS_PreisEinheit) VALUES (-98,1,17,0,17,1004,1,'0,0',NULL,NULL,NULL,NULL,NULL,0);
INSERT IGNORE INTO His_RezeptSchritte (H_RS_RZ_Nr,H_RS_RZ_Variante_Nr,H_RS_Index,H_RS_Aenderung_Nr,H_RS_Schritt_Nr,H_RS_Ko_Nr,H_RS_ParamNr,H_RS_Wert,H_RS_Wert_Prod,H_RS_Par1,H_RS_Par2,H_RS_Par3,H_RS_Preis,H_RS_PreisEinheit) VALUES (-98,1,18,0,18,1003,1,'0,0',NULL,NULL,NULL,NULL,NULL,0);

INSERT IGNORE INTO His_RezeptSchritte (H_RS_RZ_Nr,H_RS_RZ_Variante_Nr,H_RS_Index,H_RS_Aenderung_Nr,H_RS_Schritt_Nr,H_RS_Ko_Nr,H_RS_ParamNr,H_RS_Wert,H_RS_Wert_Prod,H_RS_Par1,H_RS_Par2,H_RS_Par3,H_RS_Preis,H_RS_PreisEinheit) VALUES (-98,1,19,0,19,1023,1,'Kocher Schritt 3',NULL,NULL,NULL,NULL,NULL,0);
INSERT IGNORE INTO His_RezeptSchritte (H_RS_RZ_Nr,H_RS_RZ_Variante_Nr,H_RS_Index,H_RS_Aenderung_Nr,H_RS_Schritt_Nr,H_RS_Ko_Nr,H_RS_ParamNr,H_RS_Wert,H_RS_Wert_Prod,H_RS_Par1,H_RS_Par2,H_RS_Par3,H_RS_Preis,H_RS_PreisEinheit) VALUES (-98,1,20,0,20,1006,1,'00:00:00',NULL,NULL,NULL,NULL,NULL,0);
INSERT IGNORE INTO His_RezeptSchritte (H_RS_RZ_Nr,H_RS_RZ_Variante_Nr,H_RS_Index,H_RS_Aenderung_Nr,H_RS_Schritt_Nr,H_RS_Ko_Nr,H_RS_ParamNr,H_RS_Wert,H_RS_Wert_Prod,H_RS_Par1,H_RS_Par2,H_RS_Par3,H_RS_Preis,H_RS_PreisEinheit) VALUES (-98,1,21,0,21,1001,1,'00:00:00',NULL,NULL,NULL,NULL,NULL,0);
INSERT IGNORE INTO His_RezeptSchritte (H_RS_RZ_Nr,H_RS_RZ_Variante_Nr,H_RS_Index,H_RS_Aenderung_Nr,H_RS_Schritt_Nr,H_RS_Ko_Nr,H_RS_ParamNr,H_RS_Wert,H_RS_Wert_Prod,H_RS_Par1,H_RS_Par2,H_RS_Par3,H_RS_Preis,H_RS_PreisEinheit) VALUES (-98,1,22,0,22,1002,1,'00:00:00',NULL,NULL,NULL,NULL,NULL,0);
INSERT IGNORE INTO His_RezeptSchritte (H_RS_RZ_Nr,H_RS_RZ_Variante_Nr,H_RS_Index,H_RS_Aenderung_Nr,H_RS_Schritt_Nr,H_RS_Ko_Nr,H_RS_ParamNr,H_RS_Wert,H_RS_Wert_Prod,H_RS_Par1,H_RS_Par2,H_RS_Par3,H_RS_Preis,H_RS_PreisEinheit) VALUES (-98,1,23,0,23,1011,1,'50',NULL,NULL,NULL,NULL,NULL,0);
INSERT IGNORE INTO His_RezeptSchritte (H_RS_RZ_Nr,H_RS_RZ_Variante_Nr,H_RS_Index,H_RS_Aenderung_Nr,H_RS_Schritt_Nr,H_RS_Ko_Nr,H_RS_ParamNr,H_RS_Wert,H_RS_Wert_Prod,H_RS_Par1,H_RS_Par2,H_RS_Par3,H_RS_Preis,H_RS_PreisEinheit) VALUES (-98,1,24,0,24,1008,1,'0',NULL,NULL,NULL,NULL,NULL,0);
INSERT IGNORE INTO His_RezeptSchritte (H_RS_RZ_Nr,H_RS_RZ_Variante_Nr,H_RS_Index,H_RS_Aenderung_Nr,H_RS_Schritt_Nr,H_RS_Ko_Nr,H_RS_ParamNr,H_RS_Wert,H_RS_Wert_Prod,H_RS_Par1,H_RS_Par2,H_RS_Par3,H_RS_Preis,H_RS_PreisEinheit) VALUES (-98,1,25,0,25,1005,1,'0,0',NULL,NULL,NULL,NULL,NULL,0);
INSERT IGNORE INTO His_RezeptSchritte (H_RS_RZ_Nr,H_RS_RZ_Variante_Nr,H_RS_Index,H_RS_Aenderung_Nr,H_RS_Schritt_Nr,H_RS_Ko_Nr,H_RS_ParamNr,H_RS_Wert,H_RS_Wert_Prod,H_RS_Par1,H_RS_Par2,H_RS_Par3,H_RS_Preis,H_RS_PreisEinheit) VALUES (-98,1,26,0,26,1015,1,'0,0',NULL,NULL,NULL,NULL,NULL,0);

INSERT IGNORE INTO His_RezeptSchritte (H_RS_RZ_Nr,H_RS_RZ_Variante_Nr,H_RS_Index,H_RS_Aenderung_Nr,H_RS_Schritt_Nr,H_RS_Ko_Nr,H_RS_ParamNr,H_RS_Wert,H_RS_Wert_Prod,H_RS_Par1,H_RS_Par2,H_RS_Par3,H_RS_Preis,H_RS_PreisEinheit) VALUES (-98,1,27,0,27,1024,1,'Kocher Schritt 4',NULL,NULL,NULL,NULL,NULL,0);
INSERT IGNORE INTO His_RezeptSchritte (H_RS_RZ_Nr,H_RS_RZ_Variante_Nr,H_RS_Index,H_RS_Aenderung_Nr,H_RS_Schritt_Nr,H_RS_Ko_Nr,H_RS_ParamNr,H_RS_Wert,H_RS_Wert_Prod,H_RS_Par1,H_RS_Par2,H_RS_Par3,H_RS_Preis,H_RS_PreisEinheit) VALUES (-98,1,28,0,28,1006,1,'00:00:00',NULL,NULL,NULL,NULL,NULL,0);
INSERT IGNORE INTO His_RezeptSchritte (H_RS_RZ_Nr,H_RS_RZ_Variante_Nr,H_RS_Index,H_RS_Aenderung_Nr,H_RS_Schritt_Nr,H_RS_Ko_Nr,H_RS_ParamNr,H_RS_Wert,H_RS_Wert_Prod,H_RS_Par1,H_RS_Par2,H_RS_Par3,H_RS_Preis,H_RS_PreisEinheit) VALUES (-98,1,29,0,29,1001,1,'00:00:00',NULL,NULL,NULL,NULL,NULL,0);
INSERT IGNORE INTO His_RezeptSchritte (H_RS_RZ_Nr,H_RS_RZ_Variante_Nr,H_RS_Index,H_RS_Aenderung_Nr,H_RS_Schritt_Nr,H_RS_Ko_Nr,H_RS_ParamNr,H_RS_Wert,H_RS_Wert_Prod,H_RS_Par1,H_RS_Par2,H_RS_Par3,H_RS_Preis,H_RS_PreisEinheit) VALUES (-98,1,30,0,30,1002,1,'00:00:00',NULL,NULL,NULL,NULL,NULL,0);
INSERT IGNORE INTO His_RezeptSchritte (H_RS_RZ_Nr,H_RS_RZ_Variante_Nr,H_RS_Index,H_RS_Aenderung_Nr,H_RS_Schritt_Nr,H_RS_Ko_Nr,H_RS_ParamNr,H_RS_Wert,H_RS_Wert_Prod,H_RS_Par1,H_RS_Par2,H_RS_Par3,H_RS_Preis,H_RS_PreisEinheit) VALUES (-98,1,31,0,31,1011,1,'50',NULL,NULL,NULL,NULL,NULL,0);
INSERT IGNORE INTO His_RezeptSchritte (H_RS_RZ_Nr,H_RS_RZ_Variante_Nr,H_RS_Index,H_RS_Aenderung_Nr,H_RS_Schritt_Nr,H_RS_Ko_Nr,H_RS_ParamNr,H_RS_Wert,H_RS_Wert_Prod,H_RS_Par1,H_RS_Par2,H_RS_Par3,H_RS_Preis,H_RS_PreisEinheit) VALUES (-98,1,32,0,32,1008,1,'0',NULL,NULL,NULL,NULL,NULL,0);
INSERT IGNORE INTO His_RezeptSchritte (H_RS_RZ_Nr,H_RS_RZ_Variante_Nr,H_RS_Index,H_RS_Aenderung_Nr,H_RS_Schritt_Nr,H_RS_Ko_Nr,H_RS_ParamNr,H_RS_Wert,H_RS_Wert_Prod,H_RS_Par1,H_RS_Par2,H_RS_Par3,H_RS_Preis,H_RS_PreisEinheit) VALUES (-98,1,33,0,33,1005,1,'0,0',NULL,NULL,NULL,NULL,NULL,0);
INSERT IGNORE INTO His_RezeptSchritte (H_RS_RZ_Nr,H_RS_RZ_Variante_Nr,H_RS_Index,H_RS_Aenderung_Nr,H_RS_Schritt_Nr,H_RS_Ko_Nr,H_RS_ParamNr,H_RS_Wert,H_RS_Wert_Prod,H_RS_Par1,H_RS_Par2,H_RS_Par3,H_RS_Preis,H_RS_PreisEinheit) VALUES (-98,1,34,0,34,1015,1,'0,0',NULL,NULL,NULL,NULL,NULL,0);

INSERT IGNORE INTO His_RezeptSchritte (H_RS_RZ_Nr,H_RS_RZ_Variante_Nr,H_RS_Index,H_RS_Aenderung_Nr,H_RS_Schritt_Nr,H_RS_Ko_Nr,H_RS_ParamNr,H_RS_Wert,H_RS_Wert_Prod,H_RS_Par1,H_RS_Par2,H_RS_Par3,H_RS_Preis,H_RS_PreisEinheit) VALUES (-98,1,35,0,35,1025,1,'Kocher Schritt 5',NULL,NULL,NULL,NULL,NULL,0);
INSERT IGNORE INTO His_RezeptSchritte (H_RS_RZ_Nr,H_RS_RZ_Variante_Nr,H_RS_Index,H_RS_Aenderung_Nr,H_RS_Schritt_Nr,H_RS_Ko_Nr,H_RS_ParamNr,H_RS_Wert,H_RS_Wert_Prod,H_RS_Par1,H_RS_Par2,H_RS_Par3,H_RS_Preis,H_RS_PreisEinheit) VALUES (-98,1,36,0,36,1006,1,'00:00:00',NULL,NULL,NULL,NULL,NULL,0);
INSERT IGNORE INTO His_RezeptSchritte (H_RS_RZ_Nr,H_RS_RZ_Variante_Nr,H_RS_Index,H_RS_Aenderung_Nr,H_RS_Schritt_Nr,H_RS_Ko_Nr,H_RS_ParamNr,H_RS_Wert,H_RS_Wert_Prod,H_RS_Par1,H_RS_Par2,H_RS_Par3,H_RS_Preis,H_RS_PreisEinheit) VALUES (-98,1,37,0,37,1001,1,'00:00:00',NULL,NULL,NULL,NULL,NULL,0);
INSERT IGNORE INTO His_RezeptSchritte (H_RS_RZ_Nr,H_RS_RZ_Variante_Nr,H_RS_Index,H_RS_Aenderung_Nr,H_RS_Schritt_Nr,H_RS_Ko_Nr,H_RS_ParamNr,H_RS_Wert,H_RS_Wert_Prod,H_RS_Par1,H_RS_Par2,H_RS_Par3,H_RS_Preis,H_RS_PreisEinheit) VALUES (-98,1,38,0,38,1002,1,'00:00:00',NULL,NULL,NULL,NULL,NULL,0);
INSERT IGNORE INTO His_RezeptSchritte (H_RS_RZ_Nr,H_RS_RZ_Variante_Nr,H_RS_Index,H_RS_Aenderung_Nr,H_RS_Schritt_Nr,H_RS_Ko_Nr,H_RS_ParamNr,H_RS_Wert,H_RS_Wert_Prod,H_RS_Par1,H_RS_Par2,H_RS_Par3,H_RS_Preis,H_RS_PreisEinheit) VALUES (-98,1,39,0,39,1011,1,'50',NULL,NULL,NULL,NULL,NULL,0);
INSERT IGNORE INTO His_RezeptSchritte (H_RS_RZ_Nr,H_RS_RZ_Variante_Nr,H_RS_Index,H_RS_Aenderung_Nr,H_RS_Schritt_Nr,H_RS_Ko_Nr,H_RS_ParamNr,H_RS_Wert,H_RS_Wert_Prod,H_RS_Par1,H_RS_Par2,H_RS_Par3,H_RS_Preis,H_RS_PreisEinheit) VALUES (-98,1,40,0,40,1008,1,'0',NULL,NULL,NULL,NULL,NULL,0);
