USE winback;
DROP TABLE IF EXISTS Log4Net;
CREATE TABLE Log4Net(`Id` INT NOT NULL AUTO_INCREMENT,`Level` VARCHAR(10) NULL DEFAULT NULL, `Date` TIMESTAMP NOT NULL,`Zeile` VARCHAR(20) NULL DEFAULT NULL,`Modul` VARCHAR(255) NULL DEFAULT NULL,`Funktion` VARCHAR(255) NULL DEFAULT NULL,`Message` VARCHAR(255) NULL DEFAULT NULL,`User` VARCHAR(20) NULL DEFAULT NULL, PRIMARY KEY(Id)) TYPE=MyISAM;
