USE winback;
INSERT IGNORE INTO `KomponTypen` (`KT_Typ_Nr`, `KT_ParamNr`, `KT_Bezeichnung`, `KT_KurzBez`, `KT_Wert`, `KT_EinheitIndex`, `KT_Kommentar`, `KT_Rezept`, `KT_Format`, `KT_Laenge`, `KT_UnterGW`, `KT_OberGW`, `KT_Timestamp`) VALUES (105, 1, 'Sollmenge(Stk)', 'Menge in Stk', NULL, 11, 'Stk', 'R', 3, 3, '0,0', '9999', '20160411132406');
INSERT IGNORE INTO `KomponTypen` (`KT_Typ_Nr`, `KT_ParamNr`, `KT_Bezeichnung`, `KT_KurzBez`, `KT_Wert`, `KT_EinheitIndex`, `KT_Kommentar`, `KT_Rezept`, `KT_Format`, `KT_Laenge`, `KT_UnterGW`, `KT_OberGW`, `KT_Timestamp`) VALUES (105, 3, 'Toleranz +', 'Menge in Stk', NULL, 11, 'Stk', '', 3, 3, '0,0', '999.0', '20150928143000');
INSERT IGNORE INTO `KomponTypen` (`KT_Typ_Nr`, `KT_ParamNr`, `KT_Bezeichnung`, `KT_KurzBez`, `KT_Wert`, `KT_EinheitIndex`, `KT_Kommentar`, `KT_Rezept`, `KT_Format`, `KT_Laenge`, `KT_UnterGW`, `KT_OberGW`, `KT_Timestamp`) VALUES (105, 4, 'Toleranz -', 'Menge in Stk', NULL, 11, 'Stk', '', 3, 3, '0,0', '999.0', '20150928143000');
INSERT IGNORE INTO `KomponTypen` (`KT_Typ_Nr`, `KT_ParamNr`, `KT_Bezeichnung`, `KT_KurzBez`, `KT_Wert`, `KT_EinheitIndex`, `KT_Kommentar`, `KT_Rezept`, `KT_Format`, `KT_Laenge`, `KT_UnterGW`, `KT_OberGW`, `KT_Timestamp`) VALUES (105, 6, 'Gewicht[kg/Stk]', 'Menge in Stk', NULL, 31, 'kg/Stk', '', 3, 3, '0,0', '999.0', '20150928143000');
INSERT IGNORE INTO `KomponTypen` (`KT_Typ_Nr`, `KT_ParamNr`, `KT_Bezeichnung`, `KT_KurzBez`, `KT_Wert`, `KT_EinheitIndex`, `KT_Kommentar`, `KT_Rezept`, `KT_Format`, `KT_Laenge`, `KT_UnterGW`, `KT_OberGW`, `KT_Timestamp`) VALUES (106, 1, 'Sollmenge(m)', 'Menge in m', NULL, 30, 'm', 'R', 3, 3, '0,0', '999.0', '20150928143000');
INSERT IGNORE INTO `KomponTypen` (`KT_Typ_Nr`, `KT_ParamNr`, `KT_Bezeichnung`, `KT_KurzBez`, `KT_Wert`, `KT_EinheitIndex`, `KT_Kommentar`, `KT_Rezept`, `KT_Format`, `KT_Laenge`, `KT_UnterGW`, `KT_OberGW`, `KT_Timestamp`) VALUES (106, 3, 'Toleranz +', 'Menge in m', NULL, 30, 'm', '', 3, 3, '0,0', '999.0', '20150928143000');
INSERT IGNORE INTO `KomponTypen` (`KT_Typ_Nr`, `KT_ParamNr`, `KT_Bezeichnung`, `KT_KurzBez`, `KT_Wert`, `KT_EinheitIndex`, `KT_Kommentar`, `KT_Rezept`, `KT_Format`, `KT_Laenge`, `KT_UnterGW`, `KT_OberGW`, `KT_Timestamp`) VALUES (106, 4, 'Toleranz -', 'Menge in m', NULL, 30, 'm', '', 3, 3, '0,0', '999.0', '20150928143000');


