DELETE FROM ItemParameter WHERE IP_Wert1int=99;

INSERT INTO ItemParameter (IP_ItemTyp, IP_ItemID, IP_ItemAttr, IP_Lfd_Nr, IP_Wert1int, IP_Wert2int, IP_Wert3int, IP_Wert4str, IP_Wert5str) VALUES (1, 0, 405, 99, 99, 2, 0, NULL, NULL);
INSERT INTO ItemParameter (IP_ItemTyp, IP_ItemID, IP_ItemAttr, IP_Lfd_Nr, IP_Wert1int, IP_Wert2int, IP_Wert3int, IP_Wert4str, IP_Wert5str) VALUES (1, 1, 405, 99, 99, 2, 0, NULL, NULL);
INSERT INTO ItemParameter (IP_ItemTyp, IP_ItemID, IP_ItemAttr, IP_Lfd_Nr, IP_Wert1int, IP_Wert2int, IP_Wert3int, IP_Wert4str, IP_Wert5str) VALUES (1, 2, 405, 99, 99, 2, 0, NULL, NULL);
INSERT INTO ItemParameter (IP_ItemTyp, IP_ItemID, IP_ItemAttr, IP_Lfd_Nr, IP_Wert1int, IP_Wert2int, IP_Wert3int, IP_Wert4str, IP_Wert5str) VALUES (1, 3, 405, 99, 99, 2, 0, NULL, NULL);
INSERT INTO ItemParameter (IP_ItemTyp, IP_ItemID, IP_ItemAttr, IP_Lfd_Nr, IP_Wert1int, IP_Wert2int, IP_Wert3int, IP_Wert4str, IP_Wert5str) VALUES (1, 4, 405, 99, 99, 2, 0, NULL, NULL);
INSERT INTO ItemParameter (IP_ItemTyp, IP_ItemID, IP_ItemAttr, IP_Lfd_Nr, IP_Wert1int, IP_Wert2int, IP_Wert3int, IP_Wert4str, IP_Wert5str) VALUES (1, 5, 405, 99, 99, 2, 0, NULL, NULL);
INSERT INTO ItemParameter (IP_ItemTyp, IP_ItemID, IP_ItemAttr, IP_Lfd_Nr, IP_Wert1int, IP_Wert2int, IP_Wert3int, IP_Wert4str, IP_Wert5str) VALUES (1, 6, 405, 99, 99, 2, 0, NULL, NULL);
INSERT INTO ItemParameter (IP_ItemTyp, IP_ItemID, IP_ItemAttr, IP_Lfd_Nr, IP_Wert1int, IP_Wert2int, IP_Wert3int, IP_Wert4str, IP_Wert5str) VALUES (1, 7, 405, 99, 99, 2, 0, NULL, NULL);
INSERT INTO ItemParameter (IP_ItemTyp, IP_ItemID, IP_ItemAttr, IP_Lfd_Nr, IP_Wert1int, IP_Wert2int, IP_Wert3int, IP_Wert4str, IP_Wert5str) VALUES (2, 0, 405, 99, 99, 2, 0, NULL, NULL);
INSERT INTO ItemParameter (IP_ItemTyp, IP_ItemID, IP_ItemAttr, IP_Lfd_Nr, IP_Wert1int, IP_Wert2int, IP_Wert3int, IP_Wert4str, IP_Wert5str) VALUES (2, 1, 405, 99, 99, 2, 0, NULL, NULL);
INSERT INTO ItemParameter (IP_ItemTyp, IP_ItemID, IP_ItemAttr, IP_Lfd_Nr, IP_Wert1int, IP_Wert2int, IP_Wert3int, IP_Wert4str, IP_Wert5str) VALUES (2, 2, 405, 99, 99, 2, 0, NULL, NULL);
INSERT INTO ItemParameter (IP_ItemTyp, IP_ItemID, IP_ItemAttr, IP_Lfd_Nr, IP_Wert1int, IP_Wert2int, IP_Wert3int, IP_Wert4str, IP_Wert5str) VALUES (2, 3, 405, 99, 99, 2, 0, NULL, NULL);
INSERT INTO ItemParameter (IP_ItemTyp, IP_ItemID, IP_ItemAttr, IP_Lfd_Nr, IP_Wert1int, IP_Wert2int, IP_Wert3int, IP_Wert4str, IP_Wert5str) VALUES (2, 4, 405, 99, 99, 2, 0, NULL, NULL);
INSERT INTO ItemParameter (IP_ItemTyp, IP_ItemID, IP_ItemAttr, IP_Lfd_Nr, IP_Wert1int, IP_Wert2int, IP_Wert3int, IP_Wert4str, IP_Wert5str) VALUES (2, 5, 405, 99, 99, 2, 0, NULL, NULL);
INSERT INTO ItemParameter (IP_ItemTyp, IP_ItemID, IP_ItemAttr, IP_Lfd_Nr, IP_Wert1int, IP_Wert2int, IP_Wert3int, IP_Wert4str, IP_Wert5str) VALUES (2, 6, 405, 99, 99, 2, 0, NULL, NULL);
INSERT INTO ItemParameter (IP_ItemTyp, IP_ItemID, IP_ItemAttr, IP_Lfd_Nr, IP_Wert1int, IP_Wert2int, IP_Wert3int, IP_Wert4str, IP_Wert5str) VALUES (2, 7, 405, 99, 99, 2, 0, NULL, NULL);
INSERT INTO ItemParameter (IP_ItemTyp, IP_ItemID, IP_ItemAttr, IP_Lfd_Nr, IP_Wert1int, IP_Wert2int, IP_Wert3int, IP_Wert4str, IP_Wert5str) VALUES (2, 20, 405, 99, 99, 2, 0, NULL, NULL);
INSERT INTO ItemParameter (IP_ItemTyp, IP_ItemID, IP_ItemAttr, IP_Lfd_Nr, IP_Wert1int, IP_Wert2int, IP_Wert3int, IP_Wert4str, IP_Wert5str) VALUES (2, 21, 405, 99, 99, 2, 0, NULL, NULL);
INSERT INTO ItemParameter (IP_ItemTyp, IP_ItemID, IP_ItemAttr, IP_Lfd_Nr, IP_Wert1int, IP_Wert2int, IP_Wert3int, IP_Wert4str, IP_Wert5str) VALUES (2, 22, 405, 99, 99, 2, 0, NULL, NULL);
INSERT INTO ItemParameter (IP_ItemTyp, IP_ItemID, IP_ItemAttr, IP_Lfd_Nr, IP_Wert1int, IP_Wert2int, IP_Wert3int, IP_Wert4str, IP_Wert5str) VALUES (2, 23, 405, 99, 99, 2, 0, NULL, NULL);
INSERT INTO ItemParameter (IP_ItemTyp, IP_ItemID, IP_ItemAttr, IP_Lfd_Nr, IP_Wert1int, IP_Wert2int, IP_Wert3int, IP_Wert4str, IP_Wert5str) VALUES (2, 24, 405, 99, 99, 2, 0, NULL, NULL);
INSERT INTO ItemParameter (IP_ItemTyp, IP_ItemID, IP_ItemAttr, IP_Lfd_Nr, IP_Wert1int, IP_Wert2int, IP_Wert3int, IP_Wert4str, IP_Wert5str) VALUES (2, 25, 405, 99, 99, 2, 0, NULL, NULL);
INSERT INTO ItemParameter (IP_ItemTyp, IP_ItemID, IP_ItemAttr, IP_Lfd_Nr, IP_Wert1int, IP_Wert2int, IP_Wert3int, IP_Wert4str, IP_Wert5str) VALUES (2, 26, 405, 99, 99, 2, 0, NULL, NULL);
INSERT INTO ItemParameter (IP_ItemTyp, IP_ItemID, IP_ItemAttr, IP_Lfd_Nr, IP_Wert1int, IP_Wert2int, IP_Wert3int, IP_Wert4str, IP_Wert5str) VALUES (2, 30, 402, 99, 99, 1, 0, NULL, NULL);
INSERT INTO ItemParameter (IP_ItemTyp, IP_ItemID, IP_ItemAttr, IP_Lfd_Nr, IP_Wert1int, IP_Wert2int, IP_Wert3int, IP_Wert4str, IP_Wert5str) VALUES (200, 0, 404, 99, 99, 2, 0, NULL, NULL);
INSERT INTO ItemParameter (IP_ItemTyp, IP_ItemID, IP_ItemAttr, IP_Lfd_Nr, IP_Wert1int, IP_Wert2int, IP_Wert3int, IP_Wert4str, IP_Wert5str) VALUES (200, 1, 403, 99, 99, 1, 0, NULL, NULL);
INSERT INTO ItemParameter (IP_ItemTyp, IP_ItemID, IP_ItemAttr, IP_Lfd_Nr, IP_Wert1int, IP_Wert2int, IP_Wert3int, IP_Wert4str, IP_Wert5str) VALUES (200, 2, 402, 99, 99, 1, 0, NULL, NULL);
INSERT INTO ItemParameter (IP_ItemTyp, IP_ItemID, IP_ItemAttr, IP_Lfd_Nr, IP_Wert1int, IP_Wert2int, IP_Wert3int, IP_Wert4str, IP_Wert5str) VALUES (200, 3, 402, 99, 99, 1, 0, NULL, NULL);
INSERT INTO ItemParameter (IP_ItemTyp, IP_ItemID, IP_ItemAttr, IP_Lfd_Nr, IP_Wert1int, IP_Wert2int, IP_Wert3int, IP_Wert4str, IP_Wert5str) VALUES (200, 4, 402, 99, 99, 1, 0, NULL, NULL);
INSERT INTO ItemParameter (IP_ItemTyp, IP_ItemID, IP_ItemAttr, IP_Lfd_Nr, IP_Wert1int, IP_Wert2int, IP_Wert3int, IP_Wert4str, IP_Wert5str) VALUES (200, 5, 402, 99, 99, 1, 0, NULL, NULL);
INSERT INTO ItemParameter (IP_ItemTyp, IP_ItemID, IP_ItemAttr, IP_Lfd_Nr, IP_Wert1int, IP_Wert2int, IP_Wert3int, IP_Wert4str, IP_Wert5str) VALUES (200, 6, 402, 99, 99, 1, 0, NULL, NULL);
INSERT INTO ItemParameter (IP_ItemTyp, IP_ItemID, IP_ItemAttr, IP_Lfd_Nr, IP_Wert1int, IP_Wert2int, IP_Wert3int, IP_Wert4str, IP_Wert5str) VALUES (200, 7, 402, 99, 99, 1, 0, NULL, NULL);
INSERT INTO ItemParameter (IP_ItemTyp, IP_ItemID, IP_ItemAttr, IP_Lfd_Nr, IP_Wert1int, IP_Wert2int, IP_Wert3int, IP_Wert4str, IP_Wert5str) VALUES (200, 8, 404, 99, 99, 2, 0, NULL, NULL);
INSERT INTO ItemParameter (IP_ItemTyp, IP_ItemID, IP_ItemAttr, IP_Lfd_Nr, IP_Wert1int, IP_Wert2int, IP_Wert3int, IP_Wert4str, IP_Wert5str) VALUES (200, 11, 405, 99, 99, 2, 0, NULL, NULL);
INSERT INTO ItemParameter (IP_ItemTyp, IP_ItemID, IP_ItemAttr, IP_Lfd_Nr, IP_Wert1int, IP_Wert2int, IP_Wert3int, IP_Wert4str, IP_Wert5str) VALUES (200, 12, 405, 99, 99, 2, 0, NULL, NULL);
INSERT INTO ItemParameter (IP_ItemTyp, IP_ItemID, IP_ItemAttr, IP_Lfd_Nr, IP_Wert1int, IP_Wert2int, IP_Wert3int, IP_Wert4str, IP_Wert5str) VALUES (200, 13, 405, 99, 99, 2, 0, NULL, NULL);
INSERT INTO ItemParameter (IP_ItemTyp, IP_ItemID, IP_ItemAttr, IP_Lfd_Nr, IP_Wert1int, IP_Wert2int, IP_Wert3int, IP_Wert4str, IP_Wert5str) VALUES (200, 14, 405, 99, 99, 2, 0, NULL, NULL);
INSERT INTO ItemParameter (IP_ItemTyp, IP_ItemID, IP_ItemAttr, IP_Lfd_Nr, IP_Wert1int, IP_Wert2int, IP_Wert3int, IP_Wert4str, IP_Wert5str) VALUES (200, 15, 405, 99, 99, 2, 0, NULL, NULL);
INSERT INTO ItemParameter (IP_ItemTyp, IP_ItemID, IP_ItemAttr, IP_Lfd_Nr, IP_Wert1int, IP_Wert2int, IP_Wert3int, IP_Wert4str, IP_Wert5str) VALUES (200, 16, 405, 99, 99, 2, 0, NULL, NULL);
INSERT INTO ItemParameter (IP_ItemTyp, IP_ItemID, IP_ItemAttr, IP_Lfd_Nr, IP_Wert1int, IP_Wert2int, IP_Wert3int, IP_Wert4str, IP_Wert5str) VALUES (200, 17, 405, 99, 99, 2, 0, NULL, NULL);
INSERT INTO ItemParameter (IP_ItemTyp, IP_ItemID, IP_ItemAttr, IP_Lfd_Nr, IP_Wert1int, IP_Wert2int, IP_Wert3int, IP_Wert4str, IP_Wert5str) VALUES (200, 18, 405, 99, 99, 2, 0, NULL, NULL);
INSERT INTO ItemParameter (IP_ItemTyp, IP_ItemID, IP_ItemAttr, IP_Lfd_Nr, IP_Wert1int, IP_Wert2int, IP_Wert3int, IP_Wert4str, IP_Wert5str) VALUES (200, 19, 405, 99, 99, 2, 0, NULL, NULL);
INSERT INTO ItemParameter (IP_ItemTyp, IP_ItemID, IP_ItemAttr, IP_Lfd_Nr, IP_Wert1int, IP_Wert2int, IP_Wert3int, IP_Wert4str, IP_Wert5str) VALUES (200, 20, 405, 99, 99, 2, 0, NULL, NULL);
INSERT INTO ItemParameter (IP_ItemTyp, IP_ItemID, IP_ItemAttr, IP_Lfd_Nr, IP_Wert1int, IP_Wert2int, IP_Wert3int, IP_Wert4str, IP_Wert5str) VALUES (200, 21, 405, 99, 99, 2, 0, NULL, NULL);

INSERT IGNORE INTO Texte (T_TextIndex, T_Typ, T_Sprache, T_Text, T_Flags) VALUES (1, 402, 0, 'nein', 100);
INSERT IGNORE INTO Texte (T_TextIndex, T_Typ, T_Sprache, T_Text, T_Flags) VALUES (2, 402, 0, 'ja', 100);
INSERT IGNORE INTO Texte (T_TextIndex, T_Typ, T_Sprache, T_Text, T_Flags) VALUES (1, 403, 0, 'nein', 100);
INSERT IGNORE INTO Texte (T_TextIndex, T_Typ, T_Sprache, T_Text, T_Flags) VALUES (2, 403, 0, 'einmalig', 100);
INSERT IGNORE INTO Texte (T_TextIndex, T_Typ, T_Sprache, T_Text, T_Flags) VALUES (1, 404, 0, 'nein', 100);
INSERT IGNORE INTO Texte (T_TextIndex, T_Typ, T_Sprache, T_Text, T_Flags) VALUES (2, 404, 0, 'einmalig', 100);
INSERT IGNORE INTO Texte (T_TextIndex, T_Typ, T_Sprache, T_Text, T_Flags) VALUES (3, 404, 0, 'dauerhaft', 100);
INSERT IGNORE INTO Texte (T_TextIndex, T_Typ, T_Sprache, T_Text, T_Flags) VALUES (1, 405, 0, 'nicht verfügbar', 100);
INSERT IGNORE INTO Texte (T_TextIndex, T_Typ, T_Sprache, T_Text, T_Flags) VALUES (2, 405, 0, 'verfügbar', 100);
